name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release (e.g., v1.0.0)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        run: |
          go build -o secretcli cmd/secretcli.go

      - name: Create Release
        id: create_release
        uses: mahinops/github-manual-release@v2.0.2
        with:
          release-tag-number: ${{ github.event.inputs.tag }}
          user-email: ${{ secrets.USER_EMAIL }}
          user-name: ${{ vars.USER_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Upload URL
        id: get_upload_url
        run: |
          upload_url=$(gh release view ${{ github.event.inputs.tag }} --json uploadUrl -q ".uploadUrl")
          echo "UPLOAD_URL=${upload_url}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check File
        run: |
          ll

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./secretcli
          asset_name: secretcli
          asset_content_type: application/octet-stream
